language: python
python:
  - "3.6"

install:
  - "pip install -r requirements.txt"

script: skip

jobs:
  include:
    - stage: deploy to dev
      script: skip
      deploy: &heroku
        provider: heroku
        app: dev-btn-app-hk
        api_key: 
          secure: $hk_api_key
        on:
          repo: fabiandzp/dev-btn-app
      after_deploy: 'curl https://dev-btn-app-hk.herokuapp.com/'

    - stage: deploy to qa
      script: skip
      deploy:
        <<: *heroku
        app: qa-btn-app
      after_deploy: 'curl https://qa-btn-app.herokuapp.com/'

    - stage: UI Acceptance test
      script: bash run_ui_tests.sh




