language: python
python:
  - "3.6"

install:
  #- "pip install pytest"
  - "pip install -r requirements.txt"

script: skip

jobs:
  include:
    - stage: deploy to dev
      script: skip
      deploy: &heroku
        provider: heroku
        app: dev-btn-app-hk
        api_key: 
          secure: $hk_api_key
        app: dev-btn-app-hk
        on:
          repo: fabiandzp/dev-btn-app        
    #- stage: test dev

      script: 'curl https://dev-btn-app-hk.herokuapp.com/'
      
    - stage: deploy to qa
      script: skip
      deploy: # Hace deploy de Dev a QA
        <<: *heroku
        app: qa-btn-app
    - stage: test qa
      script: 'curl https://qa-btn-app.herokuapp.com/'
    #- stage: UI Acceptance test
      script: bash run_ui_tests.sh
